In [18]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col , upper , avg

spark = SparkSession.builder.appName("ExerciciosSpark").getOrCreate()

df = spark.read.csv("DataFrame.csv",header=True,inferSchema=True)
print("5 primeiras linhas do DataFrame")
df.show(5)

print("Pessoas com mais de 25 anos")
df.filter(col("Idade") > 25).show()

print("Selecionando apenas Nome e Cidade")
df_selecionar=df.select("Nome","Cidade")
df_selecionar.show()

df_ordenar=df.orderBy(col("Idade").desc())
print("Ordem decrescente de Idade")
df_ordenar.show()

df_maiusculo=df.withColumn("Nome",upper(col("Nome")))
print("Coluna Nome em maiúsculo")
df_maiusculo.show()

idade_media=df.agg(avg("Idade").alias("Idade Média"))
print("Idade média")
idade_media.show()

pessoas_por_cidade=df.groupBy("Cidade").count().alias("Contagem")
print("Contagem de pessoas por cidade")
pessoas_por_cidade.show()

5 primeiras linhas do DataFrame
+------------+-----+--------------+
|        Nome|Idade|        Cidade|
+------------+-----+--------------+
| Lucas Silva|   29|     Sao Paulo|
|Maria Santos|   34|Rio de Janeiro|
|Jo�o Pereira|   22|Belo Horizonte|
|   Ana Costa|   27|      Salvador|
|  Pedro Lima|   31|      Curitiba|
+------------+-----+--------------+
only showing top 5 rows

Pessoas com mais de 25 anos
+--------------+-----+--------------+
|          Nome|Idade|        Cidade|
+--------------+-----+--------------+
|   Lucas Silva|   29|     Sao Paulo|
|  Maria Santos|   34|Rio de Janeiro|
|     Ana Costa|   27|      Salvador|
|    Pedro Lima|   31|      Curitiba|
|  Marcos Rocha|   33|  Porto Alegre|
|   Clara Ramos|   28|     Fortaleza|
|  Rafael Souza|   30|        Manaus|
|Isabela Farias|   26|      Brasilia|
+--------------+-----+--------------+

Selecionando apenas Nome e Cidade
+--------------+--------------+
|          Nome|        Cidade|
+--------------+--------------+
|   Lucas Silva|     Sao Paulo|
|  Maria Santos|Rio de Janeiro|
|  Jo�o Pereira|Belo Horizonte|
|     Ana Costa|      Salvador|
|    Pedro Lima|      Curitiba|
|   Julia Alves|        Recife|
|  Marcos Rocha|  Porto Alegre|
|   Clara Ramos|     Fortaleza|
|  Rafael Souza|        Manaus|
|Isabela Farias|      Brasilia|
+--------------+--------------+

Ordem decrescente de Idade
+--------------+-----+--------------+
|          Nome|Idade|        Cidade|
+--------------+-----+--------------+
|  Maria Santos|   34|Rio de Janeiro|
|  Marcos Rocha|   33|  Porto Alegre|
|    Pedro Lima|   31|      Curitiba|
|  Rafael Souza|   30|        Manaus|
|   Lucas Silva|   29|     Sao Paulo|
|   Clara Ramos|   28|     Fortaleza|
|     Ana Costa|   27|      Salvador|
|Isabela Farias|   26|      Brasilia|
|   Julia Alves|   25|        Recife|
|  Jo�o Pereira|   22|Belo Horizonte|
+--------------+-----+--------------+

Coluna Nome em maiúsculo
+--------------+-----+--------------+
|          Nome|Idade|        Cidade|
+--------------+-----+--------------+
|   LUCAS SILVA|   29|     Sao Paulo|
|  MARIA SANTOS|   34|Rio de Janeiro|
|  JO�O PEREIRA|   22|Belo Horizonte|
|     ANA COSTA|   27|      Salvador|
|    PEDRO LIMA|   31|      Curitiba|
|   JULIA ALVES|   25|        Recife|
|  MARCOS ROCHA|   33|  Porto Alegre|
|   CLARA RAMOS|   28|     Fortaleza|
|  RAFAEL SOUZA|   30|        Manaus|
|ISABELA FARIAS|   26|      Brasilia|
+--------------+-----+--------------+

Idade média
+-----------+
|Idade Média|
+-----------+
|       28.5|
+-----------+

Contagem de pessoas por cidade
+--------------+-----+
|        Cidade|count|
+--------------+-----+
|     Fortaleza|    1|
|      Curitiba|    1|
|Belo Horizonte|    1|
|     Sao Paulo|    1|
|      Salvador|    1|
|        Recife|    1|
|        Manaus|    1|
|      Brasilia|    1|
|Rio de Janeiro|    1|
|  Porto Alegre|    1|
+--------------+-----+